"""
Agent 2 — SQL Validator
=======================
Stage 1: Deterministic whitelist check (pure Python + regex, no LLM).
         Every table reference and dotted column reference in the SQL is
         checked against the real Glue schema. Anything not in the schema
         raises ValueError immediately — this gate cannot be bypassed by
         a confident model.

Stage 2: Athena dialect repair (LLM, narrow scope).
         Only runs if Stage 1 passes. Claude is asked only to fix Presto/
         Athena syntax issues. Forbidden from changing names or logic.

Why regex instead of sqlparse token walking?
    sqlparse's recursive token tree loses keyword context across recursion
    boundaries. In testing this caused three classes of false positives:
      1. Table names re-classified as columns when _walk() re-entered an
         Identifier node with no prev_kw context.
      2. CTE names (after WITH) flagged as unknown columns when referenced
         in later FROM clauses.
      3. Column aliases (AS cnt, AS total_projects) treated as real column
         references and blocked.
    Regex extraction — FROM/JOIN targets, CTE names, dotted refs — is
    simpler and produces zero false positives on all patterns Agent 1
    actually generates.
"""

import json
import re
import logging
from typing import Dict, List, Set

import boto3

logger = logging.getLogger(__name__)

BEDROCK  = boto3.client("bedrock-runtime")
MODEL_ID = "anthropic.claude-3-haiku-20240307-v1:0"

CONFIDENCE_THRESHOLD = 0.7

DIALECT_REPAIR_PROMPT = """
You are an AWS Athena (Presto SQL) dialect repair engine.
Your ONLY job is to fix SQL syntax so it runs on Athena.

RULES:
- Do NOT change any table names or column names.
- Do NOT change logic, filters, JOINs, or aggregations.
- Fix dialect issues only, for example:
    * STR_TO_DATE  -> DATE_PARSE
    * TOP N        -> LIMIT N
    * GETDATE()    -> CURRENT_DATE
    * ISNULL       -> COALESCE
    * [col]        -> "col"
    * `col`        -> "col"
- Output ONLY valid JSON, no markdown, no explanation.

Return:
{
  "repaired_sql": "<corrected SQL>",
  "changes_made": ["<description of each change>"]
}

If no changes needed, echo original SQL and set changes_made to [].
""".strip()


# SQL keywords and function names — skip as column identifiers
_SKIP_NAMES: Set[str] = {
    "select","from","where","and","or","not","in","like","between","is","null",
    "true","false","case","when","then","else","end","order","by","group",
    "having","limit","offset","union","all","distinct","as","on","set","with",
    "inner","left","right","outer","cross","join","full","exists","any","into",
    "row_number","over","partition","count","sum","avg","min","max","coalesce",
    "cast","try_cast","date_parse","date_format","date_diff","date_add",
    "current_date","current_timestamp","year","month","day","hour","lower",
    "upper","trim","length","substr","substring","concat","replace","round",
    "floor","ceil","abs","if","nullif","greatest","least","regexp_like",
    "regexp_extract","strpos","contains","element_at","array_agg","arbitrary",
    "approx_distinct","cardinality","split","try","typeof",
    # Common CTE / alias names generated by Agent 1
    "rn","cnt","total","result","latest","base","ranked","deduped","cte",
}

# Short aliases Agent 1 commonly uses (p, lb, lp etc).
# These are skipped as dotted-ref qualifiers UNLESS the qualifier exactly
# matches a real Glue table name (in which case we DO check the column).
_SHORT_ALIASES: Set[str] = {
    "p","b","a","s","t","e","c","l","la","lb","lp","lc","pa","lb","ls",
}


# ── Public entry point ────────────────────────────────────────────────────────

def validate_and_repair(agent1_output: dict, glue_schema: dict) -> str:
    """
    Validate and dialect-repair Agent 1's SQL.

    Args:
        agent1_output: Full dict from generate_sql() — needs sql_query + confidence_score.
        glue_schema:   { table: [col, ...] } from glue_service.get_glue_schema_dict().

    Returns:
        Validated, dialect-repaired SQL string ready to send to Athena.

    Raises:
        ValueError on empty SQL, low confidence, unknown real tables, or
        unknown columns on a directly-referenced real table.
    """
    sql = agent1_output.get("sql_query", "").strip()
    if not sql:
        raise ValueError("Agent 1 returned empty sql_query.")

    confidence = agent1_output.get("confidence_score", 0.0)
    if confidence < CONFIDENCE_THRESHOLD:
        raise ValueError(
            f"Agent 1 confidence too low: {confidence:.2f} < {CONFIDENCE_THRESHOLD}. "
            "Question may be ambiguous or outside the schema."
        )

    _whitelist_check(sql, glue_schema)
    return _repair_dialect(sql)


# ── Stage 1: whitelist check ──────────────────────────────────────────────────

def _whitelist_check(sql: str, glue_schema: dict) -> None:
    allowed_tables  = {t.lower() for t in glue_schema}
    allowed_columns = {
        t.lower(): {c.lower() for c in cols}
        for t, cols in glue_schema.items()
    }

    sql_l     = sql.lower()
    cte_names = _extract_cte_names(sql_l)
    violations = []

    # ── 1. Table reference check ──────────────────────────────────────────────
    for tbl in _extract_table_refs(sql_l):
        if tbl in cte_names:        # CTE — not a real Glue table
            continue
        if tbl in _SKIP_NAMES:
            continue
        if tbl not in allowed_tables:
            violations.append(f"Unknown table: '{tbl}'")

    # ── 2. Dotted column reference check (qualifier.column) ───────────────────
    # Only block when the qualifier is a known real table name — everything
    # else (aliases, CTEs, short aliases) is skipped to avoid false positives.
    for ref in _extract_dotted_refs(sql_l):
        qualifier, col = ref.split(".", 1)
        if qualifier in cte_names:
            continue
        if qualifier in _SKIP_NAMES:
            continue
        if qualifier in _SHORT_ALIASES and qualifier not in allowed_columns:
            continue  # short alias, not a real table name
        if qualifier in allowed_columns:
            if col not in allowed_columns[qualifier] and col != "*" and col not in _SKIP_NAMES:
                violations.append(f"Unknown column: '{qualifier}.{col}'")

    if violations:
        raise ValueError(
            "Whitelist check failed — identifiers not in Glue schema:\n" +
            "\n".join(f"  • {v}" for v in violations)
        )

    real_tables = _extract_table_refs(sql_l) - cte_names - _SKIP_NAMES
    logger.info(f"Agent 2 Stage 1 passed. Real tables: {sorted(real_tables)}")


# ── Regex extraction helpers ──────────────────────────────────────────────────

def _extract_cte_names(sql_l: str) -> Set[str]:
    """All CTE names defined in WITH name AS ( ... ) blocks."""
    return set(re.findall(r'(?:^with|,)\s+(\w+)\s+as\s*\(', sql_l, re.MULTILINE))


def _extract_table_refs(sql_l: str) -> Set[str]:
    """All identifiers immediately following FROM or JOIN keywords."""
    refs = set()
    for m in re.finditer(r'(?:from|join)\s+([\w`"\[\]]+)', sql_l):
        name = m.group(1).strip('"`[]').lower()
        if name not in _SKIP_NAMES and name not in _SHORT_ALIASES:
            refs.add(name)
    return refs


def _extract_dotted_refs(sql_l: str) -> Set[str]:
    """All qualifier.column patterns (e.g. p.record_id, projects.mwe)."""
    refs = set()
    for m in re.finditer(r'\b(\w+)\.(\w+)\b', sql_l):
        q, c = m.group(1).lower(), m.group(2).lower()
        if q.isdigit() or c.isdigit():
            continue
        refs.add(f"{q}.{c}")
    return refs


# ── Stage 2: dialect repair ───────────────────────────────────────────────────

def _repair_dialect(sql: str) -> str:
    body = {
        "anthropic_version": "bedrock-2023-05-31",
        "system": DIALECT_REPAIR_PROMPT,
        "messages": [{"role": "user", "content": f"Fix dialect issues:\n\n{sql}"}],
        "max_tokens": 2000,
        "temperature": 0,
    }
    response = BEDROCK.invoke_model(modelId=MODEL_ID, body=json.dumps(body))
    raw  = json.loads(response["body"].read())
    text = re.sub(r"```json|```", "", raw["content"][0]["text"]).strip()

    try:
        result   = json.loads(text)
        repaired = result.get("repaired_sql", "").strip()
        changes  = result.get("changes_made", [])
        if not repaired:
            logger.warning("Dialect repair returned empty SQL — using original.")
            return sql
        if changes:
            logger.info(f"Dialect repair made {len(changes)} change(s): {changes}")
        return repaired
    except (json.JSONDecodeError, KeyError):
        logger.warning("Dialect repair returned non-JSON — using original SQL.")
        return sql
